### ISSUE TITLE
Poor training results

### ISSUE THREAD

**Issue by Valkyrie1215** [kcheng1021/GaussianPro#12]
This is my training code:

python train.py -s D:\data\xiaobieshu -m output/xiaobieshu --eval --port 6009 --eval --propagation_interval 50 --propagated_iteration_begin 1000 --propagated_iteration_after 6000 --patch_size 20 --lambda_l1_normal 0.001 --lambda_cos_normal 0.001 --normal_loss --depth_loss --eval --flatten_loss --position_lr_init 0.00016 --scaling_lr 0.001 --percent_dense 0.0005 --port 1021

the data is 36 wraparound shots, 3dgs can be trained very well, why is gaussianpro still bad after 7000 rounds
![image](https://github.com/kcheng1021/GaussianPro/assets/104125743/d5d413cf-8e84-4dd9-8c05-3028f5697f69)

**Comment by flamehaze1115** [comment]
Could you please upload your images and poses, so we can have a test to see potential problems?

**Comment by kcheng1021** [comment]
Is your training data arranged in time order? i.e., is it a sequence of video frames? The current version does not support unordered image sets. Additionally, if you could upload your data or provide more information, we would be able to replicate the issue or make a better assessment. @Valkyrie1215

**Comment by Valkyrie1215** [comment]
here is my data:
link：https://pan.baidu.com/s/17h4PRL3JEcfLz1Kb8Ck-eQ?pwd=boip 
code：boip

**Comment by xxlong0** [comment]
Our current repo only supports ordered images, since we need to know which images are overlapped with each other. You can mamually sort the images or use a video clip. The support to unordered images will be finished soon.

**Comment by kcheng1021** [comment]
@Valkyrie1215 

1. I have tried to use 3DGS to train your data. It seems that its test image is bad while training image fits well. Have your splitted the train/test when training 3DGS? i.e. setting --eval.  Here is my result: https://drive.google.com/file/d/120XbWJr_gkei84BFym-3pGM77T6vPR5X/view?usp=sharing.

2. Due to the sparse viewpoints and small overlap between adjacent frames in your data, some parameters need to be adjusted (It is not mentioned in current version). In the train.py file, on line 179, the condition cost >= 2 should be changed to cost >= 1. I am also trying the GaussianPro on your scene, the results will be updated once finished.

**Comment by Valkyrie1215** [comment]
@kcheng1021 
Thank you very much for taking the time to answer my questions. I will study the points you mentioned as soon as possible.

**Comment by kcheng1021** [comment]
Sure. Feel free to ask and leave message in this issue. In the current stage, your probem is solved and I will close the issue. The issue willl be reopened if needed.
